name: codeshastra
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  csv: ^5.0.1
  percent_indicator: ^4.2.3
  google_sign_in: ^6.1.0
  firebase_auth: ^4.4.0
  fluttertoast: ^8.2.1
  cloud_firestore: ^4.5.0
  google_nav_bar: ^5.0.6
  flutter_spinwheel: ^0.1.0
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
